# Generated by Django 4.1.5 on 2023-02-22 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.PositiveIntegerField(default=0)),
                ("currency", models.CharField(default="NGN", max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("amount", models.FloatField()),
                ("txn_ref", models.CharField(max_length=200, unique=True)),
                ("verified", models.BooleanField(default=False)),
                (
                    "payment_options",
                    models.CharField(
                        choices=[
                            ("paystack", "paystack"),
                            ("flutterwave", "flutterwave"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "payment_plan",
                    models.CharField(
                        choices=[
                            ("Standard 1", "Standard 1"),
                            ("Standard 2", "Standard 2"),
                            ("Standard 3", "Standard 3"),
                            ("Gold 1", "Gold 1"),
                            ("Gold 2", "Gold 2"),
                        ],
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Payments",
                "ordering": ("-created_at",),
            },
        ),
    ]
