# Generated by Django 4.1.5 on 2023-02-22 04:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import hitcount.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Apartment Title"
                    ),
                ),
                ("property_ref", models.CharField(editable=False, max_length=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Apartments", "Apartments"),
                            ("Hostels", "Hostels"),
                            ("Flats", "Flats"),
                            ("Commercial Properties", "Commercial Properties"),
                            ("Event Centers", "Event Centers"),
                            ("Self Contain", "Self Contain"),
                            ("Houses", "Houses"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "_type",
                    models.CharField(
                        choices=[("Rent", "Rent"), ("Sale", "Sale")],
                        default="Rent",
                        max_length=255,
                        verbose_name="type",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("state", models.CharField(max_length=500)),
                ("address", models.CharField(max_length=1000)),
                ("map_link", models.URLField(blank=True, null=True)),
                ("descriptions", models.TextField(blank=True, null=True)),
                ("specifications", models.JSONField(blank=True, null=True)),
                ("is_available", models.BooleanField(default=True)),
                ("verified", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["category"],
            },
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        upload_to="apartment/videos",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp4", "mkv", "3gp"]
                            )
                        ],
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Media",
            },
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="apartments")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="apartments.apartment",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_updated"],
            },
        ),
    ]
